title: "Jean Ong<br>Wueng Kee"
logo: /assets/img/jean_circ.png
description: >
  wuengkee_ong@sutd.edu.sg <br> 
  +31 659312777 | +65 88797570 
  <hr> 
  <a href='https://urbanjeans.github.io/resume_portfolio/RESUME.html'>Resume</a> <br><br> 
  <a href='https://urbanjeans.github.io/resume_portfolio/'>Projects</a> <br><br> 
  <hr>
show_downloads: false
theme: jekyll-theme-minimal
