title: "Jean Ong<br>Wueng Kee"
logo: /assets/img/jean_circ.png
description: "wuengkee_ong@sutd.edu.sg <br> +31 659312777 | +65 88797570 <hr> <a href='https://github.com/urbanjeans'>Resume</a> <hr><hr> <a href='https://github.com/urbanjeans'>Projects</a>"
#show_downloads: true
theme: jekyll-theme-minimal
